site_name: x_xy
site_url: https://x_xy.com/
nav:
  - Home: index.md
  - API Reference: api.md
theme:
    name: material
    features:
        - navigation.sections  # Sections are included in the navigation on the left.
        - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
        - header.autohide  # header disappears as you scroll
    palette:
        # Light mode / dark mode
        # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
        # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
        - scheme: default
          primary: white
          accent: amber
          toggle:
             icon: material/weather-night
             name: Switch to dark mode
        - scheme: slate
          primary: black
          accent: amber
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          heading_level: 3
          show_root_toc_entry: false
          docstring_section_style: list
          show_signature_annotations: true
          signature_crossrefs: true
