site_name: x_xy
site_url: https://x_xy.com/
site_description: The documentation for the x_xy software library.

nav:
  - 'index.md'
  - Basic API: 
    - System: api/system.md
    - State: api/state.md
    - Transform: api/transform.md
    - Generator: api/generator.md
    - Rendering: api/rendering.md
  - Advanced API: 
    - Register New Joint Types: api/register_joint_types.md
    - subpkgs.exp_data: api/exp_data.md
    - subpkgs.sim2real: api/sim2real.md
    - subpkgs.sys_composer: api/sys_composer.md
  - API (everything else):
    - algebra.md
    - base.md

theme:
    name: material
    features:
        - navigation.sections  # Sections are included in the navigation on the left.
        - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
        - header.autohide  # header disappears as you scroll
    palette:
        # Light mode / dark mode
        # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
        # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
        - scheme: default
          primary: white
          accent: amber
          toggle:
             icon: material/weather-night
             name: Switch to dark mode
        - scheme: slate
          primary: black
          accent: amber
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode

markdown_extensions:
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - toc:
        permalink: "¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4  # Prevents h5, h6 (i.e. methods) from showing up in the TOC.

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - search  # default search plugin; needs manually re-enabling when using any other plugins
    - autorefs  # Cross-links to headings
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                options:
                    show_root_heading: true
                    show_root_full_path: false
                    show_if_no_docstring: false
                    show_signature_annotations: false
                    members_order: source  # order methods according to their order of definition in the source code, not alphabetical order
                    heading_level: 4  # Makes everything top-level be <h4>. Child entries will be <h5> etc., but because of toc_depth, above, (deliberately) won't appear in the TOC.
                    show_bases: false